#!/usr/bin/env node
/*
 * Verify a Nimiq signed-message authentication challenge.
 *
 * Reads one JSON object from stdin:
 *   { message, public_key, signature }
 *
 * The signature format follows Nimiq's signed-message convention:
 *   sha256("\x16Nimiq Signed Message:\n" + message.length + message)
 *
 * On success this returns the public key's canonical Nimiq address. Nothing
 * secret is handled here: the private key stays inside Nimiq Pay.
 */

import * as NimiqModule from '@nimiq/core';

const Nimiq = (NimiqModule.default && NimiqModule.default.PublicKey)
  ? NimiqModule.default
  : NimiqModule;

function readStdin() {
  return new Promise((resolve, reject) => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => { data += chunk; });
    process.stdin.on('end', () => resolve(data));
    process.stdin.on('error', reject);
  });
}

function ok(payload) {
  process.stdout.write(`${JSON.stringify({ ok: true, ...payload })}\n`);
}

function fail(error) {
  const message = error && error.message ? error.message : String(error);
  process.stdout.write(`${JSON.stringify({ ok: false, message })}\n`);
  process.exitCode = 1;
}

function cleanHex(value, field, expectedBytes) {
  const hex = String(value || '').trim().replace(/^0x/i, '').toLowerCase();
  if (!/^[0-9a-f]+$/.test(hex) || hex.length !== expectedBytes * 2) {
    throw new Error(`${field} must be ${expectedBytes} bytes of hexadecimal data`);
  }
  return hex;
}

function userFriendlyAddress(address) {
  if (address && typeof address.toUserFriendlyAddress === 'function') {
    return address.toUserFriendlyAddress();
  }
  if (address && typeof address.toString === 'function') {
    return address.toString();
  }
  return String(address || '');
}

function signedMessageBytes(message) {
  // Authentication challenges generated by NimHunt are ASCII, so JS string
  // length and UTF-8 byte length are deliberately identical here.
  const prefix = '\x16Nimiq Signed Message:\n';
  return Nimiq.BufferUtils.fromUtf8(`${prefix}${message.length}${message}`);
}

function verifySignedMessage(message, publicKeyHex, signatureHex) {
  const publicKey = Nimiq.PublicKey.fromHex
    ? Nimiq.PublicKey.fromHex(publicKeyHex)
    : new Nimiq.PublicKey(Nimiq.BufferUtils.fromHex(publicKeyHex));
  const signature = Nimiq.Signature.fromHex
    ? Nimiq.Signature.fromHex(signatureHex)
    : new Nimiq.Signature(Nimiq.BufferUtils.fromHex(signatureHex));
  const hash = Nimiq.Hash.computeSha256(signedMessageBytes(message));

  let valid = false;
  if (typeof signature.verify === 'function') {
    valid = Boolean(signature.verify(publicKey, hash));
  } else if (typeof publicKey.verify === 'function') {
    const hashBytes = typeof hash.serialize === 'function' ? hash.serialize() : hash;
    valid = Boolean(publicKey.verify(signature, hashBytes));
  } else {
    throw new Error('This @nimiq/core build does not expose signature verification');
  }

  if (!valid) throw new Error('Invalid Nimiq authentication signature');

  const address = userFriendlyAddress(publicKey.toAddress());
  if (!address) throw new Error('Could not derive a Nimiq address from the public key');
  return address;
}

async function main() {
  const raw = await readStdin();
  const payload = JSON.parse(raw || '{}');
  const message = String(payload.message || '');
  if (!message || message.length > 2048) throw new Error('message is required');

  const publicKeyHex = cleanHex(payload.public_key, 'public_key', 32);
  const signatureHex = cleanHex(payload.signature, 'signature', 64);
  const address = verifySignedMessage(message, publicKeyHex, signatureHex);

  ok({
    address,
    public_key: publicKeyHex,
  });
}

main().catch(fail);
